const HomePageStyles = {
  bigBox: { minHeight: "100vh", background: "#0D0259" },
  appBar: {
    backgroundColor: "transparent",
    boxShadow: "none",
    py: 3,
  },
  toolbar: {
    justifyContent: "space-between",
  },
  logoBox: {
    display: "flex",
    alignItems: "center",
    ml: 3,
  },
  logoImage: {
    height: "60px",
    marginRight: 8,
    backgroundColor: "transparent",
  },
  logoText: {
    color: "#00f0ff",
    fontWeight: 600,
  },
  tabs: {
    background: "linear-gradient(to right, #573bff, #713eff)",
    borderRadius: "999px",
    p: "4px",
    minHeight: "40px",
    "& .MuiTabs-indicator": {
      display: "none",
    },
    "& .MuiTab-root": {
      minHeight: "32px",
      minWidth: "100px",
      color: "#00f0ff",
      fontWeight: 600,
      textTransform: "none",
      transition: "0.3s",
      mr: 5,
      "&:last-child": {
        mr: 0,
      },
      "&.Mui-selected": {
        color: "white",
        backgroundColor: "#6a6dff",
        borderRadius: "999px",
      },
    },
  },
  loginButton: {
    backgroundColor: "#00f0ff",
    boxShadow: "0px 0px 20px rgba(5, 242, 219, 0.5)",
    color: "#000",
    fontWeight: "bold",
    borderRadius: "8px",
    textTransform: "none",
    px: 4,
    mx: 5,
    "&:hover": {
      backgroundColor: "#00e0e0",
    },
  },
  heroSection: (backgroundImage) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    px: 8,
    py: 8,
    minHeight: "500px",
    backgroundImage: `url(${backgroundImage})`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "white",
    gap: 6,
    position: "relative",
    "&::before": {
      content: '""',
      position: "absolute",
      inset: 0,
      background: "rgba(13, 2, 89, 0.7)",
      zIndex: 0,
      borderRadius: 0,
    },
  }),
  heroContent: {
    position: "relative",
    zIndex: 1,
    maxWidth: "50%",
  },
  heroTitle: {
    fontWeight: "bold",
    mb: 2,
  },
  heroSubtitle: {
    mb: 5,
  },
  getStartedButton: {
    backgroundColor: "#00f0ff",
    boxShadow: "0px 0px 20px rgba(5, 242, 219, 0.5)",
    color: "#000",
    fontWeight: "bold",
    borderRadius: "8px",
    textTransform: "none",
    px: 5,
    py: 1.5,
    "&:hover": {
      backgroundColor: "#00e0e0",
    },
  },
  whatWeDoSection: {
    textAlign: "center",
    py: 10,
    px: 4,
    color: "#fff",
  },
  whatWeDoTitle: {
    fontWeight: "bold",
    mb: 2,
  },
  whatWeDoSubtitle: {
    mb: 10,
    color: "#cfcfcf",
  },
  whatWeDoCardWrapper: {
    width: 300,
  },

  howItWorksSection: {
    mx: "auto",
    maxWidth: "1100px",
    px: 3,
    py: 8,
    textAlign: "center",
    color: "#fff",
    mb: 5,
  },
  howItWorksTitle: {
    fontWeight: "bold",
    mb: 2,
  },
  howItWorksSubtitle: {
    mb: 6,
    color: "#cfcfcf",
  },
  stepCard: {
    borderTop: "4px solid #05F2DB",
    borderBottom: "4px solid #05F2DB",
    borderLeft: "2px solid #05F2DB",
    borderRight: "2px solid #05F2DB",
    boxShadow: "0px 0px 20px rgba(5, 242, 219, 0.5)",
    borderRadius: "16px",
    backgroundColor: "rgba(0, 0, 0, 0.05)",
    p: 3,
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
  },
  stepCircle: {
    backgroundColor: "#05F2DB",
    color: "#0D0259",
    fontWeight: "bold",
    borderRadius: "50%",
    width: "40px",
    height: "40px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    mb: 1.5,
    fontSize: "18px",
  },
  stepTitle: {
    fontWeight: "bold",
    color: "#05F2DB",
    mb: 1,
  },
  stepText: {
    color: "#ccc",
  },
  getStartedButtonCentered: {
    backgroundColor: "#05F2DB",
    boxShadow: "0px 0px 20px rgba(5, 242, 219, 0.5)",
    color: "#000",
    fontWeight: "bold",
    borderRadius: "10px",
    textTransform: "none",
    px: 8,
    py: 2,
    mt: 7,
    "&:hover": {
      backgroundColor: "#00e6cc",
    },
  },
  whoWeAreSection: {
    py: 10,
    px: 4,
    textAlign: "center",
  },
  whoWeAreTitle: {
    fontWeight: "bold",
    color: "#fff",
    mb: 2,
  },
  whoWeAreSubtitle: {
    mb: 6,
    color: "#cfcfcf",
  },
  teamCardContainer: {
    position: "relative",
    pt: 6,
  },
  teamCard: {
    p: 2,
    pt: 8,
    borderRadius: "20px",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    color: "#fff",
    textAlign: "left",
    backdropFilter: "blur(10px)",
    minHeight: 170,
    maxWidth: 430,
    position: "relative",
    border: "3px solid #05F2DB",
    boxShadow: "0px 0px 20px rgba(5, 242, 219, 0.5)",
  },
  teamAvatar: {
    width: 120,
    height: 120,
    position: "absolute",
    top: 0,
    left: 20,
    transform: "translateY(-50%)",
    border: "3px solid #05F2DB",
  },
  teamCardContent: {
    pl: "80px",
    mt: 2,
  },
  teamName: {
    fontWeight: "bold",
  },
  teamRole: {
    mb: 1,
    color: "#9f9fff",
  },
  teamInfo: {
    mb: 1,
    color: "#dcdcdc",
  },
  teamEmail: {
    color: "#aaa",
  },
  cardcontent: {
    borderRadius: "20px",
    p: 2,
    borderTop: "4px solid #05F2DB",
    borderBottom: "4px solid #05F2DB",
    backgroundColor: "rgba(0, 0, 0, 0.05)",
    boxShadow: "0 8px 24px rgba(0, 0, 0, 0.3)",
    "& > div": {
      borderRadius: "18px",
      p: 2,
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      color: "#fff",
      height: "100%",
    },
  },
  cardcontentTitle: { fontWeight: "bold", mb: 1 },
  cardcontentText: { color: "#b0b0b0" },

  FooterContainer: {
    backgroundColor: "#0B005A",
    color: "#fff",
    py: 5,
    px: 10,
    boxShadow: "0px 0px 20px rgba(5, 242, 219, 0.5)",
  },
  logoSection: {
    display: "flex",
    alignItems: "center",
    gap: 1,
    mb: 2,
  },
  sectionTitle: {
    fontWeight: "bold",
    marginBottom: "8px",
  },
  emailInput: {
    padding: "10px",
    borderRadius: 5,
    border: "none",
    flexGrow: 1,
  },
  subscribeButton: {
    backgroundColor: "#00E5FF",
    color: "#000",
    fontWeight: "bold",
  },
  footerBottom: {
    textAlign: "center",
    marginTop: 4,
    borderTop: "1px solid rgba(255,255,255,0.2)",
    paddingTop: 2,
  },
};

export default HomePageStyles;
